name: prosper
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  image_picker: ^0.8.7+5
  path: ^1.8.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  file_picker: ^8.1.4
  archive: ^3.6.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - backend/assets/covers/
    - backend/assets/fonts/

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: backend/assets/fonts/timesnewromanpsmt.ttf
    
    - family: Montserrat
      fonts:
        - asset: backend/assets/fonts/Montserrat-Black.ttf
          weight: 900
    
    - family: CormorantGaramond
      fonts:
        - asset: backend/assets/fonts/CormorantGaramond-Bold.ttf
          weight: 700
    
    - family: Merriweather
      fonts:
        - asset: backend/assets/fonts/Merriweather-Black.ttf
          weight: 900